document.writeln("<html>");
document.writeln("");
document.writeln("<head>");
document.writeln("<meta http-equiv=\"Content-Type\" content=\"text\/html; charset=gb2312\">");
document.writeln("<style><!--");
document.writeln("td,body,table {font-family: \"宋体\"; font-size: 12px;}");
document.writeln("A:link {text-decoration: underline; color: #000088;}");
document.writeln("A:visited {text-decoration: underline; color: #000088;}");
document.writeln("A:active {text-decoration: underline; color: #FF0000;}");
document.writeln("A:hover {text-decoration: underline; color: #FF0000;}");
document.writeln("--><\/style>");
document.writeln("");
document.writeln("<base target=\"main5566\">");
document.writeln("");
document.writeln("<\/head>");
document.writeln("");
document.writeln("<body topmargin=\"3\" leftmargin=\"3\" bgcolor=\"#FFFFFF\" onload=\"js();\">");
document.writeln("");
document.writeln("<div align=\"center\">");
document.writeln("");
document.writeln("<table border=\"0\" cellpadding=\"3\" cellspacing=\"2\" width=\"100%\">");
document.writeln("  <tr>");
document.writeln("    <td id=\"abc\" width=\"100%\"><table border=\"0\" cellspacing=\"0\" width=\"100%\"");
document.writeln("    bordercolor=\"#000000\" bordercolorlight=\"#0E6DBC\" bordercolordark=\"#FFFFFF\">");
document.writeln("      <tr height=\"20\" align=\"center\">");
document.writeln("        <td width=\"4%\" height=\"20\"><a href=\"http://www.luhui.net/cn/jczs\"><font color=\"#FF00FF\">军事<\/font><\/a><\/td>");
document.writeln("        <td width=\"4%\"><a href=\"http://www.luhui.net/cn/rich\"><font color=\"#0000FF\">证券<\/font><\/a><\/td>");
document.writeln("        <td width=\"4%\"><a href=\"http://www.luhui.net/cn/finance\"><font color=\"#ff0000\">财经<\/font><\/a><\/td>");
document.writeln("        <td width=\"4%\"><a href=\"http://www.luhui.net/intl\">国际<\/a><\/td>");
document.writeln("        <td width=\"4%\"><a href=\"http://www.luhui.net/cn/ent\"><font color=\"#ff0000\">娱乐<\/font><\/a><\/td>");
document.writeln("        <td width=\"4%\"><a href=\"http://www.luhui.net/include\">内文<\/a><\/td>");
document.writeln("        <td width=\"4%\"><a href=\"http://www.luhui.net/cn/pctel\">火车<\/a><\/td>");
document.writeln("        <td width=\"4%\"><a href=\"http://www.luhui.net/cn/tttrip\">旅游<\/a><\/td>");
document.writeln("        <td width=\"4%\"><a href=\"http://www.luhui.net/cn/fo_luhui_index.asp\"><font color=\"#008000\">礼佛<\/font><\/a><\/td>");
document.writeln("        <td width=\"4%\"><a href=\"http://www.luhui.net/cn/vivi\">集藏<\/a><\/td>");
document.writeln("        <td width=\"4%\"><a href=\"http://www.luhui.net/cn/arti\"><font color=\"#ff0000\">文学<\/font><\/a><\/td>");
document.writeln("        <td width=\"4%\"><a href=\"http://www.luhui.net/cn/sports\"><font color=\"#0000ff\">体育<\/font><\/a><\/td>");
document.writeln("        <td width=\"4%\"><a href=\"http://www.luhui.net/upload\"><font color=\"#ff0000\">资源<\/font><\/a><\/td>");
document.writeln("        <td width=\"4%\"><a href=\"http://www.luhui.net/cn/zhaopin\"><font color=\"#0000ff\">人才<\/font><\/a><\/td>");
document.writeln("        <td width=\"4%\"><a href=\"http://www.luhui.net/cn/fy\">翻译<\/a><\/td>");
document.writeln("        <td width=\"4%\"><a href=\"http://www.luhui.net/cn/texiao\"><font color=\"#ff0000\">特效<\/font><\/a><\/td>");
document.writeln("        <td width=\"4%\"><a href=\"http://www.luhui.net/cn/mobile\">手机<\/a><\/td>");
document.writeln("        <td width=\"4%\"><a href=\"http://www.luhui.net/cn/downloads\"><font color=\"#0000ff\">下载<\/font><\/a><\/td>");
document.writeln("        <td width=\"4%\"><a href=\"http://www.luhui.net/cn/life\"><font color=\"#ff0000\">生活<\/font><\/a><\/td>");
document.writeln("        <td width=\"4%\"><a href=\"http://www.luhui.net/cn/index\">汉文<\/a><\/td>");
document.writeln("        <td width=\"4%\"><a href=\"http://www.luhui.net/cn/zhuanghuang\">装修<\/a><\/td>");
document.writeln("        <td width=\"4%\"><a href=\"http://www.luhui.net/cn/ftp\"><font color=\"#ff0000\">FTP<\/font><\/a><\/td>");
document.writeln("        <td width=\"4%\"><a href=\"http://www.luhui.net/cn/stock\"><font color=\"#ff0000\">科技<\/font><\/a><\/td>");
document.writeln("        <td width=\"4%\"><a href=\"http://www.luhui.net/cn/code\">源码<\/a><\/td>");
document.writeln("        <td width=\"4%\"><a href=\"http://www.luhui.net/cn/free\"><font color=\"#ff0000\">拼音<\/font><\/a><\/td>");
document.writeln("      <\/tr>");
document.writeln("      <tr height=\"20\" align=\"center\">");
document.writeln("        <td height=\"60\" colspan=\"5\" rowspan=\"3\">");
document.writeln("		<a style=\"color: #000066; text-decoration: none\" href=\"http://www.luhui.net/webhp/search.asp?keyword=%C2%B3%F2%B3\">");
document.writeln("		<img height=\"60\" src=\"http://www.luhui.net/luhuiIntegratedDataCenter/luhuinetimages012.gif\" width=\"160\" border=\"0\"><\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/vod\">VOD<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/music\"><font color=\"#008000\">音乐<\/font><\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/comic\">动漫<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/sh\">诗画<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/photo\">图典<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/dv_dpo\">生死<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/ip?keyword=ip\">ip<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/IE\">IE<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/MTV\">MTV<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/en\">英语<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/b2b\">硬件<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/digi\">数码<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/house\">房产<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/jp\">日搜<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/pc\">电脑<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/cars\">车族<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/train\">培训<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/UploadFace\">文档<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/health\">健康<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/host\">建站<\/a><\/td>");
document.writeln("      <\/tr>");
document.writeln("      <tr height=\"20\" align=\"center\">");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/tousu\">投诉<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/qq\">ＱＱ<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/seo\">SEO<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/album\">贺卡<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/tech\"><font color=\"#FF00FF\">答疑<\/font><\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/tb\">国学<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/digital\">摄影<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/yuming\">域命<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/tuya\">涂鸦<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/desktop\">桌面<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/guide\">偏方<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/swf\"><font color=\"#FF00FF\">闪客<\/font><\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/data\">数据<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/shop\">商城<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/sms\"><font color=\"#0000FF\">短信<\/font><\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/joy\">写真<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/ceshi\">心理<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/post\"><font color=\"#FF00FF\">区号<\/font><\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/bb\">电子<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/qi\">奇疋<\/a><\/td>");
document.writeln("      <\/tr>");
document.writeln("      <tr height=\"20\" align=\"center\">");
document.writeln("        <td><a href=\"http://www.luhui.net/skin\"><font color=\"#008080\">skin<\/font><\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/tupian\">图片<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/happy\">快乐<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/xz\"><font color=\"#734272\">星座<\/font><\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/mms\">流体<\/a><\/td>");
document.writeln("        <td align=\"center\"><a href=\"http://www.luhui.net/cn/kiddy\">亲子<\/a><\/td>");
document.writeln("        <td align=\"center\"><a href=\"http://www.luhui.net/cn/joke\">笑话<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/bank\">银行<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/rent\"><font color=\"#FF00FF\">租房<\/font><\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/blog\">博客<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/mail\">邮箱<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/f1?keyword=F1\">F1<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/parking\">驿站<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/echance\">创业<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/love\">寻欢<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/eat\"><font color=\"#808000\">美食<\/font><\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/newchat\">医学<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/weather\">天文<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/bt\">变态<\/a><\/td>");
document.writeln("        <td><a href=\"http://www.luhui.net/cn/book\">成语<\/a><\/td>");
document.writeln("      <\/tr>");
document.writeln("    <\/table>");
document.writeln("    <\/td>");
document.writeln("  <\/tr>");
document.writeln("<\/table>");
document.writeln("<\/div>");
document.writeln("<\/body>");
document.writeln("<\/html>")